### ISSUE TITLE
Unsupported major.minor version when using 0.5.0 version of VCFComp

### ISSUE THREAD

**Issue by ddemaeyer** [data-intuitive/vcf-comp-deploy#2]
Running VCFComp on spark 1.6.0, Java 7 and Scala 2.10 results in this exception: 

java.lang.UnsupportedClassVersionError: org/tmoerman/adam/fx/avro/SnpEffAnnotations : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

Probably the new version is compiled against Java 8?

**Comment by tverbeiren** [comment]
This probably has to do with the Java version used to start the notebook. Better to use Java 8 as suggested.
